# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import p2pseed_pb2 as p2pseed__pb2


class P2pSeedStub(object):
    """python -m grpc_tools.protoc --python_out=. --grpc_python_out=. -I. p2pseed.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/P2pSeed/Hello',
                request_serializer=p2pseed__pb2.HelloRequest.SerializeToString,
                response_deserializer=p2pseed__pb2.HelloResponse.FromString,
                )
        self.FindOnlineNode = channel.unary_unary(
                '/P2pSeed/FindOnlineNode',
                request_serializer=p2pseed__pb2.FindOnlineNodeRequest.SerializeToString,
                response_deserializer=p2pseed__pb2.FindOnlineNodeResponse.FromString,
                )


class P2pSeedServicer(object):
    """python -m grpc_tools.protoc --python_out=. --grpc_python_out=. -I. p2pseed.proto
    """

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOnlineNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2pSeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=p2pseed__pb2.HelloRequest.FromString,
                    response_serializer=p2pseed__pb2.HelloResponse.SerializeToString,
            ),
            'FindOnlineNode': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOnlineNode,
                    request_deserializer=p2pseed__pb2.FindOnlineNodeRequest.FromString,
                    response_serializer=p2pseed__pb2.FindOnlineNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'P2pSeed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class P2pSeed(object):
    """python -m grpc_tools.protoc --python_out=. --grpc_python_out=. -I. p2pseed.proto
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/P2pSeed/Hello',
            p2pseed__pb2.HelloRequest.SerializeToString,
            p2pseed__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindOnlineNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/P2pSeed/FindOnlineNode',
            p2pseed__pb2.FindOnlineNodeRequest.SerializeToString,
            p2pseed__pb2.FindOnlineNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
